name: Outfit Generator CI/CD
on: [push, pull_request]

jobs:
  test:
    name: "Run Tests"
    runs-on: [self-hosted, linux]
    container: ubuntu:22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          make test

  build-deb:
    name: "Build Debian Package"
    runs-on: [self-hosted, linux]
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build package
        run: |
          make build-deb
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: outfit-generator-deb
          path: ./outfit-generator-v1.0.0.deb

  lint:
    name: "Lint Package"
    runs-on: [self-hosted, linux]
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install lintian
        run: |
          apt-get update
          apt-get install -y lintian
          
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: outfit-generator-deb
          
      - name: Lint package
        run: |
          make lint
          
      - name: Save lint results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: |
            lintian-output.txt
